name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: stajdb
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5433/stajdb

    steps:
    - name: Kodu çek
      uses: actions/checkout@v4

    - name: Go kurulumu
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Modülleri indir
      run: go mod download

    - name: Testleri çalıştır
      run: go test -v ./...

    - name: End-to-End Test
      run: go test -v e2e_test.go
